services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container-getresults
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: getresults
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin-getresults
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql-container-getresults
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

volumes:
  mysql-data:

networks:
  getresults-network:
