services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container-getresults
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: getresults
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  mysql-data:

networks:
  getresults-network:
