version: '3.8'

services:
  mysql:
    image: mysql:8.0.33-oracle
    container_name: mysql-container-getresults
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: getresults
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.2.1
    container_name: phpmyadmin-getresults
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      PMA_HOST: mysql-container-getresults
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

  python_scraper:
    image: cedsanc/python-scraper-getresults:latest
    container_name: python-scraper-getresults
    depends_on:
      - mysql
    ports:
      - "5000:5000"
    environment:
      DB_HOST: mysql-container-getresults
      DB_USER: app_user
      DB_PASSWORD: app_password
      DB_NAME: getresults

  spring_api:
    image: cedsanc/spring-api-getresults:latest
    container_name: spring-api-getresults
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container-getresults:3306/getresults
      SPRING_DATASOURCE_USERNAME: app_user
      SPRING_DATASOURCE_PASSWORD: app_password

volumes:
  mysql-data:

networks:
  getresults-network:
